dist: trusty
jdk: openjdk15
language: java
services:
   - postgresql
   - docker
env:
   global:
      - secure: "Jj9OM79fCyyGeFOjdFDhWsEpu25jP57TGmnvojVtLpxeRLiGmVtWSpKMkThHltBJfC7a7apY8Sma2+KUldIea02q/DSZ9FwNLvv5kZmU7OyIngIOVelvhFcKq3u7BqrN/mRGVBICkMZoCWtxJorMXx8rZ3wkIR/CneWHPcppVvu6PF/LD1ky9QbeEr/P/FvfrOuJJFnmW49tth3HMyCydp4ZBnD3fJLpzqHBGmhS1sIij5u9/kTJbvDV/IX41sUxgLfb5lR1762OMdjZ/l5MLUgmC6GSv0T1slB95DJhLH1dK4VIiv4VBJz4gfEUGT/hJr0hWlzYEfrxa/PwGakwlFMtXpRFmQG3mIx+EiZ5WFHn3r1osa4tXPyqd+AbysOEM6FsM1XK7CT0g4F81xqf2+4nqtUvG861FP4l5DlHQgM9jiXyXPSly2gifd5AH0C7RLLCaseavDLeoKsb/T5FoXL0HLny+NW7WNbVFFZPZX6bdAg20lsfAE3dMXmF+DF/i88HYncWrOcFW5NANH3sLSvvtM9w701+3k1micaVVO4Z5KTej1xBdrWqVWijMPoOG7RZBv9ve55AP612DYKYi91B44cfm13hur72mZ83Qb+kXD9VqN3ABr5XLATkL77v1ufSDhZYWi/sIf0rqd+0dGfhID78BiuFyPPb1WM2LL0="
      - secure: "HuBk69XxJ40CsT0xEWuE2UeHbj+AyDAclShdMXe+Azf38zy57wYvK+NJkc3jYakRBqXUBifO5L7TLENwR3pfbDWOSpV5EHzhZKli9XWd0O5+H4uqUJTSWq/zsLiI8ln4en31M1XIVjtBX42Mq9aWfLZr2IFWER299Aote8/+GhyszByHk6+qb34/6F36znTixVMk2dRM3uEcvbdf4HONGLezuQ5lcDu0tbDt7CzjTdwmU7iZPt7qDc526a0k2Z049q1fGzRTBo1gwb+3JGDVY13yrKuu2rnrrhG76V0X7CbnyUcl6SCFRLZUKW5pOgEqvaA3fiT04tQSFJXBUlzJXw40Pawu+J/N2s46wyh1/KmJLwnltOPnHqyT1ZM7P793L9iFcY/ZURsSoU8c5tm0b14YI2c3DLx1FHQibJVMHPdKjfTKV6ycSyomWIZMEB8WzSyhe0Jr5iLgSdNJo2uR23+hg5o8U5qSiwv/Owy17iy1JOCWEsmxjXvZyZJtofWfVOSz4vQJTm6gWoW9WCTHLjDyNZA9Q+g04Cj1LnYgLyrABKWX7wm+j0dFi+4W3LcDsAzpAJgJjIuXYJ9l4puVMruum0rKyGHflbv3MD0hv5J2tMqTFk75XPi7itvSMbypt8Cve40PduKHQ42I+d4xxn33frtQQQb3IpW/1dil59s="
      - secure: "tDtg/tLgyaIn8KpM4pomEFiNySPwSup2YNjOjf6qHpype2Hs9e70AJb1hlHIVNNX9/Cns2ZpS8QLSAvFVoKsTyLZj5Y4237O8yvbw5rnZ+rVRuYg2JwFhMLO2Ni0rWZKmWmUeRc9Ith+VXNd5eyy8JS+BE/UxN2YDOxEL6OjLefZ4AnwMBT9noxcX7rFOtuuPbtTVW4T3wekLTU8auvM/TN/GdAe6G54iF6qLC9V18S7kjq7Z/DgNVvfJKFZO2/l67Ph0clmh1d9EQn5iRYrRKJeao6wkgnT0uY5KwyVOkaBk0BAGNxdpF2a4I09ZYL4CgadN0FdoUqj+e7P2UIpoHeO5IrTp/NOV24IteQZZegshZqskMByBv/RxmmiUX/BM66FkkhtjbpYJp7zMguoXmcaGJDNKK7h9AAgIMdoiomXxZoo+LyRnfqysRZtEmWIkBG1VnPhxXI1NQ3N3u92Qk+2m/+ip4Q2sjQsdcfH4DE/7RIrF+1bdfYrFTC58GxFtR2fId9+vxnAhxzmJpR89gbtrMWKJYcYAeYqB2zv9J6gasCIGLik1cKJ0t6Ak8qmgT6XzU/TwElvmd76LnYXXsAqEyVx9nUiCeX7I3SCOFFadwUXwXl2Hn/6MuZlBfeh9ARXZQ/LYPG/JkCpg5etiLMsKf31+/FB6v1nGN58TGI="
      - COMMIT=${TRAVIS_COMMIT::7}

addons:
   sonarcloud:
      organization: "zipa455-simpleapi"
      token:
         secure: "CokpSQmjV0lM+utBcMxBX+I2hSHMrdaxQwlvPeWBRbpovNq0kEr8wsONp79G+OH3vI9QmPO1z9YCPmW7NiVaxUIkO3F6q0a7ISmyOVlskmXkevJGQ7ku7h/ghArVLwB7Gb00K/+S/1zhe6kHn7Jaep//SvdaeecElODS+eUMN34vw8flj+VKKAJLchuhOFB1jFfjkF/aJl6q/inP7zwPVYUae5hiUVcC+72CmpHpzMtWxJWoVs/ct6I1Ek6lt06TTrT+j15/xu3SHBqhMi1JDArt+s3ngzJMP8nFNUngNWeDH5LxRMteTFZQhTAiOm02mf1fTjqOE3iSjQAi3Uik+htf/oR8b4+DCI+iGUAU9T7DDXG2vif4IlywtF4vybam1X1xnjwokX4HNsGSGlQfC8i3+IQZB4chsEotgqrxIKT6KfT4ItXvOrFKwIKIUA9+TK8IBCRGxfW2R6zZpbuRd2Knm76bwDXajtShEux1hzD0ReDzRjVFuQPbDsyC/WNfFC/YeUgCr67fY0QlFCoNXVkge9xP2uhypLXp/Au7dfEqnmHfdAUf1rpoCiRn4Zni+11/rceQO8HsKRh/+MURobsjZzJ25WrwQkNM6LVbCRwxwRVkPOPI/0vPmcCTAnevPPOjxoRWFkZTaYhLZgORB+ytcbkPHEJqsXwcEIBNE3c="

script:
   - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=zipa455_simpleapi

after_success:
   - docker login -u $DOCKER_USER -p $DOCKER_PASS
   - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
   - export IMAGE_NAME=zipa455/zipa455-simpleapi
   - docker build -t $IMAGE_NAME:latest .
   - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
   - docker push $IMAGE_NAME:$TAG

deploy:
   provider: heroku
   api_key: $HEROKU_API_KEY
   app: zipa455-simpleapi