version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=simpledb
      - POSTGRES_HOST=postgres
    restart: unless-stopped
    networks: ['mynetwork']
  simpleapi:
    image: simpleapi:latest
    container_name: simple
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    networks: ['mynetwork']
volumes:
  postgres-data:
networks: {mynetwork: {}}